Week9
pesto-students/p1-ruhan-khandakar-ShashankSuresh pull request #14
Opened 2022-06-05 15:54 UTC by ruhankhandakar

2022-06-18 05:53 UTC, ShashankSuresh commented
@ruhankhandakar `Week-9/todo/src/components/index.jsx` - this is an empty file, do you need this?

2022-06-18 06:41 UTC, ShashankSuresh commented
Im able to add an empty Note. We will have to handle this condition. 

Also, can we have 2 notes with the same Title?

![image](https://user-images.githubusercontent.com/13508322/174426228-d77c8566-e0f6-4ced-972a-f628cb492e65.png)

2022-06-19 03:54 UTC, ruhankhandakar commented
@ShashankSuresh fixed the empty case. and for the duplicate -> I tried to copy google keeps, and there they support duplicate notes. If you want I'll add duplicate handling.

2022-06-19 12:45 UTC, ShashankSuresh requested changes

2022-06-19 12:45 UTC, ShashankSuresh commented on Week-9/todo/src/context/index.js
> +    console.log("allUpdatedNotes", allUpdatedNotes);
Please remove `console.log` statement.

2022-06-19 12:45 UTC, ShashankSuresh commented on Week-9/todo/src/context/index.js
> +    console.log("updatedNote", updatedNote);
Please remove `console.log` statement.

2022-06-19 12:45 UTC, ShashankSuresh commented on Week-9/todo/src/context/index.js
> +    console.log("allUpdatedNotes", allUpdatedNotes);
Please remove `console.log` statement.

2022-06-19 12:45 UTC, ShashankSuresh commented on Week-9/todo/src/serviceWorkerRegistration.js
> +              console.log(
Please remove `console.log` statement.

2022-06-19 12:45 UTC, ShashankSuresh commented on Week-9/todo/src/serviceWorkerRegistration.js
> +              console.log("Content is cached for offline use.");
Please remove `console.log` statement.

2022-06-22 14:35 UTC, merged