Week10
pesto-students/p1-ruhan-khandakar-ShashankSuresh pull request #16
Opened 2022-06-19 10:34 UTC by ruhankhandakar

2022-06-24 07:44 UTC, ShashankSuresh commented
It would be great if you can attach a few screenshots of the app :) @ruhankhandakar

2022-06-24 07:46 UTC, ShashankSuresh requested changes
The UI looks neat and professional. Great job. 
Can you please check if it supports responsiveness? 

![image](https://user-images.githubusercontent.com/13508322/175488698-09f0377a-cc66-4ac2-af9b-3f51ca8c2bf8.png)

2022-06-24 07:48 UTC, ShashankSuresh commented
If I type "www.google.com" and click on the button to shorten the URL, the box is still editable

![image](https://user-images.githubusercontent.com/13508322/175489000-56e283d0-0bc4-4c0c-9227-19f040f1ca57.png)

2022-06-24 07:48 UTC, ShashankSuresh commented
Can we please update this? It still has the default React logo. 

![image](https://user-images.githubusercontent.com/13508322/175489064-9a43821b-98be-41cf-b6b9-74b04da96fab.png)

2022-06-24 07:49 UTC, ShashankSuresh commented
![image](https://user-images.githubusercontent.com/13508322/175489125-3ec4997c-a6ad-4a2e-8a7b-e78506531706.png)

Can this be an anchor tag? Better UI UX :)

2022-06-24 08:02 UTC, ShashankSuresh requested changes

2022-06-24 08:02 UTC, ShashankSuresh commented on Week-10/shortly/src/components/Footer/Footer.jsx
> +        <img src="/logo192.png" alt="shortly" className="h-[100px] w-[100px]" />
Have you considered creating atom components for img and div which have common styles and passing props so that it can be reused in several components where yo dont have to declare the styles. 

```
import React from "react";

const Image = (props) => {
  const { src = "", alt = "image", className = "h-[100px] w-[100px]" } = props;
  return <img src={src} alt={alt} className={className} />;
};

export default Image;
```

2022-06-24 08:02 UTC, ShashankSuresh commented on Week-10/shortly/src/App.js
> +      <Routes>
This looks good but in the future if you have multiple routes this file will become big and hence maintenance will be a nightmare. Can we create a RouteList.js file and also have a common component which has a loop to loop through the List of routes we provide as an array?

2022-06-24 08:02 UTC, ShashankSuresh commented on Week-10/shortly/src/components/Shortner/Input.jsx
> +      style={{
Can we remove in-line styles?

2022-06-24 08:02 UTC, ShashankSuresh commented on Week-10/shortly/src/utils/index.js
> +export const isUrlValid = (url) => {
Any specific reason to have it named as `index.js` as apposed to `utils.js` ?

2022-06-24 08:02 UTC, ShashankSuresh commented on Week-10/shortly/src/components/Shortner/helpers.js
> +export const getShortenResponse = async (url) => {
Can we have this in `utils.js `file?

2022-06-25 09:09 UTC, ruhankhandakar commented
> Can we please update this? It still has the default React logo.
> 
> ![image](https://user-images.githubusercontent.com/13508322/175489064-9a43821b-98be-41cf-b6b9-74b04da96fab.png)

I think it's cache issue, because I've changed favicon

2022-06-25 16:01 UTC, ruhankhandakar commented
@ShashankSuresh done all changes

2022-06-26 10:57 UTC, ShashankSuresh requested changes

2022-06-26 10:57 UTC, ShashankSuresh commented on Week-10/shortly/src/utils/utils.js
> +export const getShortenResponse = async (url) => {
Kindly incorporate custom hook for API calls. 

https://codesandbox.io/s/eloquent-panna-qt3eee?file=/src/useApi.js

2022-06-26 10:58 UTC, ShashankSuresh requested changes

2022-06-26 10:58 UTC, ShashankSuresh commented on Week-10/shortly/src/App.js
> +import "./App.css";
Good practice to import css files at the end.

2022-06-26 13:44 UTC, ShashankSuresh approved these changes
Great work :) Keep it up. Approved..

2022-06-27 09:16 UTC, ShashankSuresh commented
@ruhankhandakar Please merge

2022-06-27 09:37 UTC, merged