Week11
pesto-students/p1-ruhan-khandakar-ShashankSuresh pull request #17
Opened 2022-06-22 12:31 UTC by ruhankhandakar

2022-06-24 08:23 UTC, ShashankSuresh requested changes

2022-06-24 08:23 UTC, ShashankSuresh commented on Week-11/redux-1/src/App.css
> +  background: rgb(42, 48, 60);
Can we use css variables?

2022-06-24 08:23 UTC, ShashankSuresh commented on Week-11/redux-1/src/App.css
> +  color: #fff;
Can we use css variables?

2022-06-24 08:23 UTC, ShashankSuresh commented on Week-11/redux-1/src/App.css
> +  background-color: #111;
Can we use css variables?

2022-06-24 08:23 UTC, ShashankSuresh commented on Week-11/redux-1/src/app/store.js
> +    theme: switchReducer,
What does 'theme' do here?

2022-06-24 08:23 UTC, ShashankSuresh commented on Week-11/redux-1/src/app/store.js
> +    theme: switchReducer,
Can we have a rootReducer? So that in the future if we have multiple reducers we dont have to worry about changing the import statement here.

2022-06-24 08:23 UTC, ShashankSuresh commented on Week-11/redux-2/src/components/common/Button.jsx
> +  console.log("rerender check");
can we please remove the console.log statement?

2022-06-24 08:23 UTC, ShashankSuresh commented on Week-11/redux-2/src/components/common/Button.jsx
> +  getPaddingOrMargin();
If this function is going to be called during component mount, can we wrap it with an `useEffect ` ?

2022-06-24 08:23 UTC, ShashankSuresh commented on Week-11/redux-2/src/features/steps/Steps.jsx
> +        bgColor="#6643b5"
Good work :)

2022-06-25 16:26 UTC, ruhankhandakar commented
@ShashankSuresh done all changes

2022-06-26 13:44 UTC, ShashankSuresh approved these changes
Great work :) Keep it up. Approved..

2022-06-26 13:44 UTC, ShashankSuresh approved these changes
Great work :) Keep it up. Approved..

2022-06-27 09:17 UTC, ShashankSuresh commented
@ruhankhandakar Please merge

2022-06-27 09:37 UTC, merged